// Post-build: writes dist/server.mjs wrapper so Hostinger's
// "Output: dist / Entry: server.mjs" config can boot the app
// with HOST=0.0.0.0. Mirrors the root-level server.mjs.
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const target = join(__dirname, '..', 'dist', 'server.mjs');

const content = `// Auto-generated by scripts/postbuild.mjs
// Hostinger startup wrapper — runs from inside dist/, forces HOST=0.0.0.0.
if (!process.env.HOST) process.env.HOST = '0.0.0.0';
if (!process.env.PORT) process.env.PORT = '3000';
await import('./server/entry.mjs');
`;

await writeFile(target, content, 'utf8');
console.log('[postbuild] wrote', target);
